import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import RootProvider from "@/lib/providers";

const gmarket = localFont({
  src: [
    {
      path: "../../public/assets/fonts/GmarketSansLight.otf",
      weight: "300",
      style: "light",
    },
    {
      path: "../../public/assets/fonts/GmarketSansMedium.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/GmarketSansBold.otf",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: {
    template: "%s | Create Next App",
    default: "Create Next App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={gmarket.className}>
        <RootProvider>
          {children}
          {modal}
          <div id="portal" />
        </RootProvider>
      </body>
    </html>
  );
}
