import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AsPathProvider } from "@/context/asPathContext";
import { ToastProvider } from "@/context/toastContext";
import { ThemeProviders } from "@/lib/providers/theme-provider";
// import { ThemeStoreProvider } from "@/lib/providers/theme-provider";

const gmarket = localFont({
  src: [
    {
      path: "../../public/assets/fonts/GmarketSansLight.otf",
      weight: "300",
      style: "light",
    },
    {
      path: "../../public/assets/fonts/GmarketSansMedium.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/assets/fonts/GmarketSansBold.otf",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={gmarket.className}>
        {/* <ThemeStoreProvider> */}
        <ThemeProviders>
          <AsPathProvider>
            <ToastProvider>
              {children}
              {modal}
              <div id="portal" />
            </ToastProvider>
          </AsPathProvider>
        </ThemeProviders>
        {/* </ThemeStoreProvider> */}
      </body>
    </html>
  );
}
